### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by Toumaniere** [agajews/ApricityOS#3]
Hello, 

I got this problem during the installation 
http://puu.sh/jyDFT/a496b848fb.png
![image](https://cloud.githubusercontent.com/assets/12683182/9220951/db8c3eb6-40d5-11e5-96a0-e4425178617c.png)

With 64bits cached iso on a usb stick.

Thanks :)

**Comment by agajews** [comment]
Could you post the contents of /tmp/cnchi.log? My guess is that at the bottom it will give you some sort of connection error. If that is the case, what has worked for me in the past is simply verifying that you can actually transfer data over the internet by loading apricityos.com in chrome.

**Comment by Toumaniere** [comment]
I can load apricityos.com with chrome
Here is the /tmp/cnchi.log file :

[2015-08-12 14:45:34] [cnchi] INFO: Using GTK v3.16.6
[2015-08-12 14:45:34] [cnchi] INFO: Using pyalpm v0.7 as interface to libalpm v9.0.1
[2015-08-12 14:45:34] [updater] WARNING: Could not find 'update.info' file. Cnchi will not be able to update itself.
[2015-08-12 14:45:35] [main_window] DEBUG: Cnchi will use '/var/cache/pacman/pkg' as a source directory for cached xz packages
[2015-08-12 14:45:35] [main_window] INFO: Using urllib to download packages
[2015-08-12 14:45:35] [main_window] INFO: Using '/usr/share/cnchi/data/packages.xml' file as package list
[2015-08-12 14:45:35] [gtkbasebox] DEBUG: Loading 'welcome' screen
[2015-08-12 14:47:27] [gtkbasebox] DEBUG: Loading 'language' screen
[2015-08-12 14:47:27] [gtkbasebox] DEBUG: Loading 'location' screen
[2015-08-12 14:47:27] [gtkbasebox] DEBUG: Loading 'check' screen
[2015-08-12 14:47:27] [gtkbasebox] DEBUG: Loading 'desktop' screen
[2015-08-12 14:47:27] [gtkbasebox] DEBUG: Loading 'features' screen
[2015-08-12 14:47:27] [gtkbasebox] DEBUG: Loading 'keymap' screen
[2015-08-12 14:47:27] [gtkbasebox] DEBUG: Loading 'timezone' screen
[2015-08-12 14:47:28] [timezone] DEBUG: We have connection. Let's get our timezone
[2015-08-12 14:47:28] [gtkbasebox] DEBUG: Loading 'ask' screen
[2015-08-12 14:47:28] [gtkbasebox] DEBUG: Loading 'automatic' screen
[2015-08-12 14:47:28] [gtkbasebox] DEBUG: Loading 'advanced' screen
[2015-08-12 14:47:28] [gtkbasebox] DEBUG: Loading 'user_info' screen
[2015-08-12 14:47:28] [gtkbasebox] DEBUG: Loading 'slides' screen
[2015-08-12 14:47:29] [timezone] DEBUG: Timezone (latitude 50.4667, longitude 5.0000) detected.
[2015-08-12 14:47:35] [check] INFO: Nous avons une connexion Internet.
[2015-08-12 14:47:35] [check] INFO: Nous sommes connectés à une source d'alimentation.
[2015-08-12 14:47:35] [check] INFO: Nous avons suffisamment d'espace disque.
[2015-08-12 14:47:36] [location] DEBUG: Selected location: French (BE), Belgium
[2015-08-12 14:47:36] [location] WARNING: Impossible de changer les paramètres régionaux 'fr_BE.UTF-8'
[2015-08-12 14:47:36] [location] WARNING: Impossible de changer les paramètres régionaux 'fr_BE'
[2015-08-12 14:47:36] [location] DEBUG: Selected country: Belgium
[2015-08-12 14:47:36] [timezone] INFO: emplacement modifié : Europe/Brussels
[2015-08-12 14:47:37] [timezone] DEBUG: timezone human zone: Brussels
[2015-08-12 14:47:37] [timezone] DEBUG: timezone country: BE
[2015-08-12 14:47:37] [timezone] DEBUG: timezone zone: Europe/Brussels
[2015-08-12 14:47:37] [timezone] DEBUG: timezone human country: Belgium
[2015-08-12 14:47:37] [timezone] DEBUG: timezone latitude: 50.5
[2015-08-12 14:47:37] [timezone] DEBUG: timezone longitude: 4.2
[2015-08-12 14:47:37] [misc] WARNING: Ne peut changer la locale en 'fr_BE.UTF-8' : unsupported locale setting
[2015-08-12 14:47:37] [misc] WARNING: Impossible de changer les paramètres régionaux 'fr_BE'
[2015-08-12 14:47:37] [misc] WARNING: unsupported locale setting
[2015-08-12 14:47:37] [misc] WARNING: Ne peut changer la locale en 'fr_BE.UTF-8' : unsupported locale setting
[2015-08-12 14:47:37] [misc] WARNING: Impossible de changer les paramètres régionaux 'fr_BE'
[2015-08-12 14:47:37] [misc] WARNING: unsupported locale setting
[2015-08-12 14:47:37] [keymap] DEBUG: Set keyboard to layout name 'Belgium' (be)
[2015-08-12 14:47:38] [keymap] DEBUG: Set keyboard to layout name 'Belgium' (be)
[2015-08-12 14:47:38] [keymap] WARNING: Command '['localectl', 'set-keymap', '--no-convert', 'be']' returned non-zero exit status 1
[2015-08-12 14:47:41] [keymap] DEBUG: Set keyboard to layout name 'Belgium' (be)
[2015-08-12 14:47:43] [automatic] DEBUG:  USB DISK 2.0 [8 GB] (/dev/sda)
[2015-08-12 14:47:43] [automatic] DEBUG: ATA TOSHIBA MK7575GS [750 GB] (/dev/sdb)
[2015-08-12 14:47:49] [automatic] INFO: Installation automatique sur /dev/sdb
[2015-08-12 14:47:49] [automatic] INFO: Cnchi installera Apricity OS sur le périphérique /dev/sdb
[2015-08-12 14:47:49] [automatic] INFO: Apricity OS installera le gestionnaire de démarrage 'gummiboot' sur le périphérique '/dev/sdb'
[2015-08-12 14:47:50] [process] DEBUG: Création des partitions et de leurs systèmes de fichiers dans /dev/sdb
[2015-08-12 14:47:50] [auto_partition] DEBUG: Taille disque totale : 715404MiB
[2015-08-12 14:47:50] [auto_partition] DEBUG: Taille de la partition Boot : 256MiB
[2015-08-12 14:47:50] [auto_partition] DEBUG: Taille de la partition Swap : 5869MiB
[2015-08-12 14:47:50] [auto_partition] DEBUG: Taille de la partition Root : 709278MiB
[2015-08-12 14:47:53] [auto_partition] DEBUG: sgdisk --new=1:0:+256M --typecode=1:EF00 --change-name=1:APRICITY_BOOT /dev/sdb
[2015-08-12 14:47:55] [auto_partition] DEBUG: sgdisk --new=2:0:+709278M --typecode=2:8300 --change-name=2:APRICITY_ROOT /dev/sdb
[2015-08-12 14:47:56] [auto_partition] DEBUG: sgdisk --new=3:0:+0M --typecode=3:8200 --change-name=3:APRICITY_SWAP /dev/sdb
[2015-08-12 14:47:57] [auto_partition] DEBUG: Disk /dev/sdb: 1465149168 sectors, 698.6 GiB
Logical sector size: 512 bytes
Disk identifier (GUID): A31AB6CB-E47E-49C3-912A-6618D6334E0D
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 1465149134
Partitions will be aligned on 2048-sector boundaries
Total free space is 2014 sectors (1007.0 KiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048          526335   256.0 MiB   EF00  APRICITY_BOOT
   2          526336      1453127679   692.7 GiB   8300  APRICITY_ROOT
   3      1453127680      1465149134   5.7 GiB     8200  APRICITY_SWAP
[2015-08-12 14:47:57] [auto_partition] DEBUG: Boot: /dev/sdb1
[2015-08-12 14:47:57] [auto_partition] DEBUG: Root: /dev/sdb2
[2015-08-12 14:47:57] [auto_partition] DEBUG: Swap: /dev/sdb3
[2015-08-12 14:47:57] [auto_partition] DEBUG: Le périphérique /dev/sdb3 aura un system de fichier swap
[2015-08-12 14:47:57] [auto_partition] DEBUG: Le périphérique /dev/sdb2 aura un system de fichier ext4
[2015-08-12 14:47:57] [auto_partition] DEBUG: Le périphérique /dev/sdb1 aura un system de fichier vfat
[2015-08-12 14:47:57] [auto_partition] DEBUG: Va formater le périphérique  /dev/sdb2 en ext4
[2015-08-12 14:48:02] [auto_partition] DEBUG: Détails du périphérique: /dev/sdb2 UUID=ca168004-e5b7-40c4-be43-b68f9cff6b6d LABEL=ApricityRoot
[2015-08-12 14:48:02] [auto_partition] DEBUG: Va formater le périphérique  /dev/sdb3 en swap
[2015-08-12 14:48:03] [auto_partition] DEBUG: Détails du périphérique: /dev/sdb3 UUID=e357eb2e-fc04-420c-ba7f-e9794b59f61e LABEL=ApricitySwap
[2015-08-12 14:48:03] [auto_partition] DEBUG: Va formater le périphérique  /dev/sdb1 en vfat
[2015-08-12 14:48:03] [auto_partition] DEBUG: Détails du périphérique: /dev/sdb1 UUID=CA31-93DD LABEL=ApricityBoo
[2015-08-12 14:48:03] [auto_partition] DEBUG: /dev/sdb1 sera monté comme /boot
[2015-08-12 14:48:03] [auto_partition] DEBUG: /dev/sdb2 sera monté comme /
[2015-08-12 14:48:03] [auto_partition] DEBUG: /dev/sdb3 sera monté comme swap
[2015-08-12 14:48:03] [auto_partition] DEBUG: Le périphérique /dev/sdb3 aura un system de fichier swap
[2015-08-12 14:48:03] [auto_partition] DEBUG: Le périphérique /dev/sdb2 aura un system de fichier ext4
[2015-08-12 14:48:03] [auto_partition] DEBUG: Le périphérique /dev/sdb1 aura un system de fichier vfat
[2015-08-12 14:48:03] [process] DEBUG: Préparer Pacman...
[2015-08-12 14:48:03] [process] DEBUG: Création d'un fichier pacman.conf temporaire pour l'architecture x86_64
[2015-08-12 14:48:05] [pac] DEBUG: database dir '/install/var/lib/pacman/sync/' does not exist, creating it
[2015-08-12 14:48:05] [pac] DEBUG: url: http://apricityos.com/apricity-core//apricity-core.db
[2015-08-12 14:48:05] [pac] DEBUG: maxsize: 26214400
[2015-08-12 14:48:05] [pac] DEBUG: opened tempfile for download: /install/var/lib/pacman/sync/apricity-core.db.part (wb)
[2015-08-12 14:48:05] [pac] DEBUG: curl returned error 0 from transfer
[2015-08-12 14:48:05] [pac] DEBUG: response code: 200
[2015-08-12 14:48:05] [pac] DEBUG: url: http://archlinux.polymorf.fr/core/os/x86_64/core.db
[2015-08-12 14:48:05] [pac] DEBUG: maxsize: 26214400
[2015-08-12 14:48:05] [pac] DEBUG: opened tempfile for download: /install/var/lib/pacman/sync/core.db.part (wb)
[2015-08-12 14:48:05] [pac] DEBUG: curl returned error 0 from transfer
[2015-08-12 14:48:05] [pac] DEBUG: response code: 200
[2015-08-12 14:48:05] [pac] DEBUG: url: http://archlinux.polymorf.fr/extra/os/x86_64/extra.db
[2015-08-12 14:48:05] [pac] DEBUG: maxsize: 26214400
[2015-08-12 14:48:05] [pac] DEBUG: opened tempfile for download: /install/var/lib/pacman/sync/extra.db.part (wb)
[2015-08-12 14:48:07] [pac] DEBUG: curl returned error 0 from transfer
[2015-08-12 14:48:07] [pac] DEBUG: response code: 200
[2015-08-12 14:48:07] [pac] DEBUG: url: http://archlinux.polymorf.fr/multilib/os/x86_64/multilib.db
[2015-08-12 14:48:07] [pac] DEBUG: maxsize: 26214400
[2015-08-12 14:48:07] [pac] DEBUG: opened tempfile for download: /install/var/lib/pacman/sync/multilib.db.part (wb)
[2015-08-12 14:48:07] [pac] DEBUG: curl returned error 0 from transfer
[2015-08-12 14:48:07] [pac] DEBUG: response code: 200
[2015-08-12 14:48:07] [pac] DEBUG: url: http://archlinux.polymorf.fr/community/os/x86_64/community.db
[2015-08-12 14:48:07] [pac] DEBUG: maxsize: 26214400
[2015-08-12 14:48:07] [pac] DEBUG: opened tempfile for download: /install/var/lib/pacman/sync/community.db.part (wb)
[2015-08-12 14:48:08] [slides] INFO: Installation avec la méthode 'automatic'
[2015-08-12 14:48:08] [slides] INFO: Updating apricity-core database
[2015-08-12 14:48:08] [slides] INFO: Updating core database
[2015-08-12 14:48:08] [slides] INFO: Updating extra database
[2015-08-12 14:48:08] [slides] INFO: Updating multilib database
[2015-08-12 14:48:08] [slides] INFO: Updating community database
[2015-08-12 14:48:09] [pac] DEBUG: curl returned error 0 from transfer
[2015-08-12 14:48:09] [pac] DEBUG: response code: 200
[2015-08-12 14:48:09] [process] DEBUG: Pacman est prêt
[2015-08-12 14:48:09] [process] DEBUG: Sélection des paquets...
[2015-08-12 14:48:09] [process] DEBUG: Ajout des paquets de bureau « gnome »
[2015-08-12 14:48:10] [process] DEBUG: Hardware module detected this drivers: ['Radeon', 'ModeSetting', 'BroadcomWl', 'ModeSetting', 'i915']
[2015-08-12 14:48:10] [process] DEBUG: Un module matériel a ajouté ces paquets : lib32-mesa-libgl broadcom-wl libva-intel-driver libva-vdpau-driver xf86-video-ati libtxc_dxtn lib32-mesa xf86-video-intel
[2015-08-12 14:48:10] [process] DEBUG: Ajout des paquets du système de fichiers
[2015-08-12 14:48:10] [process] DEBUG: Rechercher des fonctions désirées par des utilisateurs et les ajouter à notre installation
[2015-08-12 14:48:10] [process] DEBUG: Tous les paquets nécessaires ont été ajoutés
[2015-08-12 14:48:10] [process] DEBUG: Adding 'gummiboot' bootloader packages
[2015-08-12 14:48:10] [process] DEBUG: ['alsa-utils', 'apricityassets', 'pamac-aur', 'yaourt-git', 'b43-fwcutter', 'baobab', 'base-devel', 'base', 'bash-completion', 'bind-tools', 'bleachbit', 'bluez-utils', 'broadcom-wl-dkms', 'btsync-gui', 'btsync', 'crda', 'cups-pk-helper', 'cups', 'dosfstools', 'eog', 'evince', 'faac', 'faad2', 'fakeroot', 'file-roller', 'filezilla', 'flac', 'gdm', 'gedit', 'gimp', 'git', 'gksu', 'gnome-backgrounds', 'gnome-bluetooth', 'gnome-calculator', 'gnome-calendar', 'gnome-color-manager', 'gnome-contacts', 'gnome-control-center', 'gnome-disk-utility', 'gnome-keyring', 'gnome-music', 'gnome-photos', 'gnome-screenshot', 'gnome-session', 'gnome-settings-daemon', 'gnome-shell-extensions', 'gnome-shell-extensions', 'gnome-shell', 'gnome-system-log', 'gnome-system-monitor', 'gnome-terminal', 'gnome-themes-standard', 'gnome-themes-standard', 'gnome-tweak-tool', 'gnome-user-docs', 'google-chrome-beta', 'google-talkplugin', 'grilo-plugins', 'gsfonts', 'gsfonts', 'gst-libav', 'gst-plugin-libde265', 'gst-plugins-bad', 'gst-plugins-base', 'gst-plugins-good', 'gst-plugins-ugly', 'gstreamer-vaapi', 'gstreamer0.10-plugins', 'gtk-engine-murrine', 'gucharmap', 'gufw', 'gzip', 'haveged', 'ice-ssb', 'inkscape', 'ipw2100-fw', 'ipw2200-fw', 'libcups', 'libdvdcss', 'libdvdnav', 'libdvdread', 'libmatroska', 'libreoffice-fresh', 'linux-firmware', 'linux-headers', 'mc', 'mesa-vdpau', 'mesa', 'modemmanager', 'mtools', 'mutter', 'nautilus', 'net-tools', 'ntp', 'network-manager-applet', 'networkmanager-openvpn', 'networkmanager-pptp', 'ntfs-3g', 'ntfs-3g', 'openssh', 'os-prober', 'pulseaudio-alsa', 'pkgfile', 'playonlinux', 'plymouth', 'polkit-gnome', 'rfkill', 'samba', 'sbackup', 'seahorse', 'smartmontools', 'splix', 'steam', 'sudo', 'sushi', 'tar', 'tlp', 'totem', 'transmission-cli', 'transmission-gtk', 'ttf-arphic-uming', 'ttf-baekmuk', 'ttf-bitstream-vera', 'ttf-dejavu', 'ttf-freefont', 'ttf-liberation', 'ufw', 'unrar', 'unzip', 'usb_modeswitch', 'wget', 'whois', 'wine', 'wireless_tools', 'wpa_actiond', 'x264', 'xdg-user-dirs-gtk', 'xdg-user-dirs-gtk', 'xf86-input-synaptics', 'xf86-video-fbdev', 'xf86-video-vesa', 'xorg-apps', 'xorg-fonts', 'xorg-server-utils', 'xorg-server', 'xorg-xinit', 'xorg-xkill', 'zd1211-firmware', 'ntp', 'lib32-mesa-libgl', 'broadcom-wl', 'libva-intel-driver', 'libva-vdpau-driver', 'xf86-video-ati', 'libtxc_dxtn', 'lib32-mesa', 'xf86-video-intel', 'gummiboot']
[2015-08-12 14:48:10] [process] DEBUG: Paquets sélectionnés
[2015-08-12 14:48:10] [process] DEBUG: Téléchargement des paquets...
[2015-08-12 14:48:10] [pac] DEBUG: loading package cache for repository 'apricity-core'
[2015-08-12 14:48:10] [pac] DEBUG: opening archive /install/var/lib/pacman/sync/apricity-core.db
[2015-08-12 14:48:10] [pac] DEBUG: added 43 packages to package cache for db 'apricity-core'
[2015-08-12 14:48:10] [pac] DEBUG: loading group cache for repository 'apricity-core'
[2015-08-12 14:48:10] [pac] DEBUG: loading package cache for repository 'core'
[2015-08-12 14:48:10] [pac] DEBUG: opening archive /install/var/lib/pacman/sync/core.db
[2015-08-12 14:48:10] [pac] DEBUG: added 209 packages to package cache for db 'core'
[2015-08-12 14:48:10] [pac] DEBUG: loading group cache for repository 'core'
[2015-08-12 14:48:10] [pac] DEBUG: loading package cache for repository 'extra'
[2015-08-12 14:48:10] [pac] DEBUG: opening archive /install/var/lib/pacman/sync/extra.db
[2015-08-12 14:48:10] [pac] DEBUG: added 3151 packages to package cache for db 'extra'
[2015-08-12 14:48:10] [pac] DEBUG: loading package cache for repository 'multilib'
[2015-08-12 14:48:10] [pac] DEBUG: opening archive /install/var/lib/pacman/sync/multilib.db
[2015-08-12 14:48:10] [pac] DEBUG: added 186 packages to package cache for db 'multilib'
[2015-08-12 14:48:10] [pac] DEBUG: loading group cache for repository 'multilib'
[2015-08-12 14:48:10] [pac] DEBUG: loading package cache for repository 'community'
[2015-08-12 14:48:10] [pac] DEBUG: opening archive /install/var/lib/pacman/sync/community.db
[2015-08-12 14:48:10] [slides] INFO: Crée la liste de paquets à télécharger...
[2015-08-12 14:48:10] [pac] DEBUG: added 4034 packages to package cache for db 'community'
[2015-08-12 14:48:10] [pac] DEBUG: loading group cache for repository 'community'
[2015-08-12 14:48:10] [pac] DEBUG: loading package cache for repository 'local'
[2015-08-12 14:48:10] [pac] DEBUG: added 0 packages to package cache for db 'local'
[2015-08-12 14:48:10] [pac] DEBUG: loading group cache for repository 'extra'
[2015-08-12 14:48:33] [metalink] ERROR: Impossible de trouver ces paquets :broadcom-wl 
[2015-08-12 14:48:33] [download] ERROR: Erreur à la création d'un métalien pour le paquet broadcom-wl. L'installation va s'arrêter
[2015-08-12 14:48:33] [process] ERROR: 'Ne peut créer la liste de paquets à télécharger. Vérifiez les logs pour obtenir des détails'
[2015-08-12 14:48:33] [process] ERROR: Traceback (most recent call last):

[2015-08-12 14:48:33] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/process.py", line 166, in run
    self.run_installation()

[2015-08-12 14:48:33] [process] ERROR:   File "/usr/share/cnchi/cnchi/misc/misc.py", line 175, in helper
    return func(*args, **kwargs)

[2015-08-12 14:48:33] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/process.py", line 359, in run_installation
    self.download_packages()

[2015-08-12 14:48:33] [process] ERROR:   File "/usr/share/cnchi/cnchi/installation/process.py", line 416, in download_packages
    self.settings)

[2015-08-12 14:48:33] [process] ERROR:   File "/usr/share/cnchi/cnchi/download/download.py", line 98, in __init__
    raise InstallError(_("Can't create download package list. Check log output for details"))

[2015-08-12 14:48:33] [process] ERROR: misc.misc.InstallError: 'Ne peut créer la liste de paquets à télécharger. Vérifiez les logs pour obtenir des détails'

[2015-08-12 14:48:33] [show_message] ERROR: 'Ne peut créer la liste de paquets à télécharger. Vérifiez les logs pour obtenir des détails'

**Comment by agajews** [comment]
It really shouldn't be trying to install broadcom-wl, but since it is I added it to the apricity-core repository. It should work now.

**Comment by Toumaniere** [comment]
Okay so what sould I do ? Simply re-launch the installer ? 
Or I have to download again an iso ?

**Comment by agajews** [comment]
You don't need to download the ISO again, as it hasn't changed. Just try to run the installer again.

**Comment by Toumaniere** [comment]
It works ! Thank you ! :+1: :)
